# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade -r requirements.txt
          
      - name: Install pyinstaller
        run: |
          python -m pip install --upgrade pyinstaller
          
      - name: Run pyinstaller
        run: |
          pyinstaller -n RDVSpoilerLogParser -F main.py

      - uses: actions/upload-artifact@v4
        with:
          name: RDVSpoilerLogParser
          path: ./RDVSpoilerLogParser*
